config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'pages#home', as: :authenticated_root
       resources :entities

       get 'pages/home'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

 

  

end

app/models/entity.rb
class Entity < ActiveRecord::Base
	#include ActiveModel::EntityTypeValidator
	belongs_to :user

	self.inheritance_column = nil

	before_save(:on => :create) do
		self.type = self.type.to_s
	end

	validates :name, :presence => true, length: { in: 3..20 }
	#validates :type, :presence => true, :if => '["Startup", "Investor", "Accelerator", "Co-worker", "R&D Center", "Service"].any?{ |o| :afreet =~ /\b#{Regexp.escape(o)}\b/ }'
	#validates_inclusion_of :type, :in => ["Startup"], :allow_nil => false
	validates :lat, :presence => true,:numericality => {:greater_than_or_equal_to => 22, :less_than_or_equal_to => 32} 
	validates :lon, :presence => true, :numericality => {:greater_than_or_equal_to => 25, :less_than_or_equal_to => 35}
	validates :address, :presence => true , length: { in: 10..80 }
	validates :description, :presence => true , length: { in: 10..400 }
	validates :year_estab, :presence => true
	validates :url, :presence => true, length: { in: 6..55 }, :format => URI::regexp(%w(http https))
	validates :user_id, :presence => true
	validates :type, :entity_type => true
	validates :year_estab, 
  		presence: true,
  		inclusion: { in: 1900..Date.today.year },
  		format: { 
    		with: /(19|20)\d{2}/i, 
    		message: "should fall between 1900 ~ current year"
  	}
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:create]

  def index
    @entities = Entity.all
  end

  def show
  end

  def new
    @entity = Entity.new
  end

  def edit
    # Populate the selected types for amends
    #@entity_types = ['Startup', 'Investor', 'Accelerator', 'Co-worker', 'R&D Center', 'Service']
    @selected_types = Entity.find(params[:id]).type.squish.gsub('"', '').gsub(']', '').gsub('[', '').split(/, /)   
  end

  def create
    if current_user.entity
      raise "You can't add more companies"
    else

      @entity = Entity.new(entity_params)
      @entity.user_id = current_user.id
      @entity.admin_verification = false
      
      respond_to do |format|
        if @entity.save
          format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
          format.json { render :show, status: :created, location: @entity }
        else
          format.html { render :new }
          format.json { render json: @entity.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    respond_to do |format|

      if @entity.update(entity_params)
          p "********************************************** "+@entity.type.to_s
        unless current_user.try(:admin)
          @entity.user_id = current_user.id
          @entity.admin_verification = false
          @entity.save
        end

        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      if current_user.try(:admin)
        params.require(:entity).permit(:name, {:type => []}, :lat, :lon, :description, :url, :address, :year_estab, :user_id, :admin_verification)
      else
        params.require(:entity).permit(:name, {:type => []}, :lat, :lon, :description, :url, :address, :year_estab)
      end
    end
end



# [\"\"]" 
# [\"\", \"Startup\"]"
# [\"\", \"Startup\", \"Accelerator\", \"Co-worker\", \"R&D Center\"]"

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div style="margin-top:4%">
  <div class="row-fluid">
    <div class="col-md-3 col-md-offset-0" style="color:white" >
    </div>
    <div class="col-md-6 col-md-offset-0">
    
      <div style="color:grey;  border: 1px #e4e4e4 solid;  padding: 20px; padding-top: 20px; border-radius: 4px; box-shadow: 0 0 6px #ccc; background-color: #fff;">

<%= bootstrap_form_for @entity , html: {id: :form_id} do |f| %>

  <div class="field">
    
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.select :type, options_for_select(["Startup", "Investor", "Accelerator", "Co-worker", "R&D Center", "Service"], :selected => @selected_types), {}, {:multiple => true, :class => "multiselect", :style => "width:450px;" }
    #f.text_field :type 
     %>
  </div>
  
  <div class="field">
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.text_area :description %>
  </div>
  <div class="field">
      <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.text_field :year_estab %>
  </div>
  <% if current_user.admin%>
  <div class="field">
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.text_field :admin_verification %>
  </div>
  <% end %>
<!-- Map goes here-->
<p style="color:red"> Right click to place a marker on the map</p>
<div style='width: 100%;'>
  <div id="multi_markers" style='width: 100%; height: 400px;'></div>
</div>

  </br>
  <div class="actions">
    <%= f.submit %>
  </div>


<script type="text/javascript">
  $(document).ready(function() {
    $('.multiselect').multiselect({

    
    onChange: function(option, checked) {
    // Get selected options.
    var selectedOptions = $('.multiselect option:selected');
     
    if (selectedOptions.length >= 3) {
    // Disable all other checkboxes.
    var nonSelectedOptions = $('.multiselect option').filter(function() {
    return !$(this).is(':selected');
    });
     
    var dropdown = $('.multiselect').siblings('.multiselect-container');
    nonSelectedOptions.each(function() {
    var input = $('input[value="' + $(this).val() + '"]');
    input.prop('disabled', true);
    input.parent('li').addClass('disabled');
    });
    }
    else {
    // Enable all checkboxes.
    var dropdown = $('.multiselect').siblings('.multiselect-container');
    $('.multiselect option').each(function() {
    var input = $('input[value="' + $(this).val() + '"]');
    input.prop('disabled', false);
    input.parent('li').addClass('disabled');
    });
    }
    }
    });
  });
</script>



<script type="text/javascript">
  var mapStyles = [
         {
            featureType: "road",
            elementType: "geometry",
            stylers: [
              { hue: "#8800ff" },
              { lightness: 100 }
            ]
          },{
            featureType: "road",
            stylers: [
              { visibility: "on" },
              { hue: "#91ff00" },
              { saturation: -62 },
              { gamma: 1.98 },
              { lightness: 45 }
            ]
          },{
            featureType: "water",
            stylers: [
              { hue: "#005eff" },
              { gamma: 0.72 },
              { lightness: 42 }
            ]
          },{
            featureType: "transit.line",
            stylers: [
              { visibility: "off" }
            ]
          },{
            featureType: "administrative.locality",
            stylers: [
              { visibility: "on" }
            ]
          },{
            featureType: "administrative.neighborhood",
            elementType: "geometry",
            stylers: [
              { visibility: "simplified" }
            ]
          },{
            featureType: "landscape",
            stylers: [
              { visibility: "on" },
              { gamma: 0.41 },
              { lightness: 46 }
            ]
          },{
            featureType: "administrative.neighborhood",
            elementType: "labels.text",
            stylers: [
              { visibility: "on" },
              { saturation: 33 },
              { lightness: 20 }
            ]
          }
        ];

        var zoomControl = true;
        var mapOptions = {
            zoom: 7,
            //minZoom: 10,
            center: new google.maps.LatLng(30.06,31.25),
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            streetViewControl: false,
            mapTypeControl: false,
            panControl: false,
            zoomControl: zoomControl,
            styles: mapStyles,
            zoomControlOptions: {
            style: google.maps.ZoomControlStyle.SMALL,
            position: google.maps.ControlPosition.LEFT_CENTER
          }
        }
        var markers;
        var handler = Gmaps.build('Google');
        handler.buildMap({
          provider: mapOptions,
          internal: {
          id: 'multi_markers'
           }
        }, function(){
        

          if($('#entity_lat').attr("value") != null)
          {
          markers = handler.addMarkers([
            {
              "lat": $('#entity_lat').attr("value"),
              "lng": $('#entity_lon').attr("value"),
              "title": "Your Company",
              "icon" : 'icons/startup.png',
              "infowindow": "<b> Your Company <b> "
            }
          ]);
        }

        google.maps.event.addListener(handler.getMap(), "rightclick", function(event) {



          var lat = event.latLng.lat();
          var lng = event.latLng.lng();
          $('#entity_lat').val(lat);
          $('#entity_lon').val(lng);
          
          
          handler.removeMarkers(markers);
          
          //add a marker

          markers = handler.addMarkers([
            {
              "lat": event.latLng.lat(),
              "lng": event.latLng.lng(),
              "title": "Your Company",
              "infowindow": "<b> Your Company <b> "
            }
          ]);
          //alert("Lat=" + lat + "; Lng=" + lng);
        });

        handler.fitMapToBounds();
        });
</script>


<% end %>


</div>
  <div class="col-md-3 col-md-offset-0" style="color:white" >
    </div>
  </div>
</div>

<!-- id="entity_lat" -->

<!-- id="entity_lon" -->

app/views/entities/edit.html.erb
<%= render 'form' %>

app/views/entities/index.html.erb
<h1>Listing entities</h1>

<table class="table table-striped table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Description</th>
      <th>Url</th>
      <th>Address</th>
      <th>Year estab</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= entity.name %></td>
        <td><%= entity.type %></td>
        <td><%= entity.lat %></td>
        <td><%= entity.lon %></td>
        <td><%= entity.description %></td>
        <td><%= entity.url %></td>
        <td><%= entity.address %></td>
        <td><%= entity.year_estab %></td>
        <td><%= entity.user_id %></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity), target: "_self"%></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<h1>New entity</h1>

<% if current_user.entity %>
	<h1> You can't create more entities</h1>
<% else %>
	<%= render 'form' %>
<% end %>

<%= link_to 'Back', authenticated_root_path, :target => "_self" %>

app/views/entities/show.html.erb
<div style="margin-top:4%">
  <div class="row-fluid">
    <div class="col-md-1 col-md-offset-0" style="color:white" >
    </div>
    <div class="col-md-10 col-md-offset-0">
    
      <div style="color:grey;  border: 1px #e4e4e4 solid;  padding: 30px; padding-top: 20px; border-radius: 4px; box-shadow: 0 0 6px #ccc; background-color: #fff;">


<p id="notice"><%= notice %></p>

<h1 style="display: inline-block"><%= @entity.name %></h1> - since  <%= @entity.year_estab %>

<p>
  <%= @entity.description %>
</p>


<% if @entity.type.include? 'Startup'%>
<%= image_tag "icons/startup.png", :title => "Startup"%>
<% end %>
<% if @entity.type.include? 'Investor'%>
<%= image_tag "icons/investor.png", :title => "Investor"%>
<% end %>
<% if @entity.type.include? 'Accelerator'%>
<%= image_tag "icons/accelerator.png", :title => "Accelerator"%>
<% end %>
<% if @entity.type.include? 'Service'%>
<%= image_tag "icons/service.png", :title => "Service"%>
<% end %>
<% if @entity.type.include? 'work'%>
<%= image_tag "icons/coworking.png", :title => "Co-worker"%>
<% end %>
<% if @entity.type.include? 'Center'%>
<%= image_tag "icons/incubator.png", :title => "R&D Center"%>
<% end %>


<p>
  <strong>Lat:</strong>
  <%= @entity.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @entity.lon %>
</p>



<p>
  <strong>Url:</strong>
  <%= link_to @entity.url, @entity.url %>
</p>

<p>
  <strong>Address:</strong>
  <%= @entity.address %>
</p>



<p>
  <% if current_user.try(:admin)%>
  <strong>User:</strong>
  <%= @entity.user_id %>
  <% end %>
</p>

<% if @entity.user.id == current_user.id %>
<p>
  <strong>Verified:</strong>
  <%= @entity.admin_verification %>
</p>
<% end %>

<% if @entity.user.id == current_user.id || current_user.admin %>
<%= link_to 'Edit', edit_entity_path(@entity) , target: "_self" %> |
<% end %>
<%= link_to 'Back', authenticated_root_path, target: "_self"%>


</div>
</div>
<div class="col-md-1 col-md-offset-0" style="color:white" >
  </div>
</div>
</div>