config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'pages#home', as: :authenticated_root
       resources :entities

       get 'pages/home'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

 

  

end

app/views/layouts/_footer.html.erb
<div class="footer" style = "background:rgba(255,255,255,0.1)">
  <div class="container">
    <p class="muted credit" style="text-align: center; color:grey" >

        &copy; 2014 <a href="https://www.linkedin.com/profile/view?id=123333477" style="color:blue">Saftophobia</a> All Rights Reserved.   |   
        <a title="Privacy Policy">Privacy Policy</a>  
         |     
        <%= link_to 'Terms of Service', "https://www.linkedin.com/profile/view?id=123333477" %> |
         <%= link_to 'About Us', "https://www.linkedin.com/profile/view?id=123333477" %> | 
         <%= link_to 'Contact', "https://www.linkedin.com/profile/view?id=123333477" %>

    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<%= nav_bar :fixed => :top, :responsive => true do %>
    <%= menu_group :pull => :right do %>
        <% if user_signed_in? %>
        	<%= drop_down "Logged in as "+ current_user.email do %>

            <% if current_user.try(:admin)%>
            <%= menu_item "Admin", entities_path , target: "_self" %> 
            <% end %>

            <% if current_user.entity %>
            <%= menu_item "My company", entity_path(current_user.entity) %>   
            <% end %>


            <%= menu_item "Sign out", destroy_user_session_path, :method => :delete %>    
        	<% end %>
        <% end %>
    <% end %>
    <%= menu_group :pull => :left do %>
        <% if user_signed_in? %>
        	<%= menu_item "Home", authenticated_root_path, target: "_self" %>
        <% end %>
    <% end %>
    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	  <title>RepresentEgypt</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
    <body>
	    <div id="wrapper">
		    <%= render 'layouts/header' %>
		    		<%= yield %> 
		    
		    <div class="footer navbar-fixed-bottom" style="color:white;">
		    	<%= render 'layouts/footer' %>	
		    </div>
	    </div>
    </body>
</html>